AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TodoGet:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: api.get_handler
      Runtime: python3.6
      CodeUri: ./todo
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:Query'
              Resource: arn:aws:dynamodb:[REGION]:[ACCOUNT_ID]:table/TodoList
      Description: Get
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: '/todo'
            Method: GET
  TodoCreate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: api.create_handler
      Runtime: python3.6
      CodeUri: ./todo
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
              Resource: arn:aws:dynamodb:[REGION]:[ACCOUNT_ID]:table/TodoList
      Description: POST
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: '/todo'
            Method: POST
  TodoUpdate:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: api.update_handler
      Runtime: python3.6
      CodeUri: ./todo
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:UpdateItem'
              Resource: arn:aws:dynamodb:[REGION]:[ACCOUNT_ID]:table/TodoList
      Description: PUT
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: '/todo'
            Method: PUT
  TodoDelete:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: api.delete_handler
      Runtime: python3.6
      CodeUri: ./todo
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetItem'
                - 'dynamodb:DeleteItem'
              Resource: arn:aws:dynamodb:[REGION]:[ACCOUNT_ID]:table/TodoList
      Description: DELETE
      Environment:
        Variables:
          TODO_TABLE: TodoList
      Events:
        ApiTodoListAPI:
          Type: Api
          Properties:
            Path: '/todo'
            Method: DELETE
 